services:

  devcontainer:
    image: mcr.microsoft.com/devcontainers/rust:latest
    container_name: devcontainer
    command: tail -f /dev/null

  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "7878:7878"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
