services:
  dev:
    build:
      image: mcr.microsoft.com/devcontainers/rust:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G

  app:
    build:
      context: ..
      dockerfile: .
    volumes:
      - ./:/app
    ports:
      - "7878:7878"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
